"""
Mythic Performance Tracker - 配置模块
"""

from .settings import (
    DUNGEON_NAME_MAP,
    DUNGEON_TIME_LIMIT,
    CLASS_COLOR_MAP,
    LAYER_COLOR_MAP,
    BROWSER_CONFIG,
    CRAWLER_CONFIG,
    FILE_PATHS,
    WCL_BASE_URL,
    SERVER_SLUG_MAP,
    BLIZZARD_BASE_URL,
    BLIZZARD_API_BASE,
    SESSION_CONFIG,
)

__all__ = [
    'DUNGEON_NAME_MAP',
    'DUNGEON_TIME_LIMIT',
    'CLASS_COLOR_MAP',
    'LAYER_COLOR_MAP',
    'BROWSER_CONFIG',
    'CRAWLER_CONFIG',
    'FILE_PATHS',
    'WCL_BASE_URL',
    'SERVER_SLUG_MAP',
    'BLIZZARD_BASE_URL',
    'BLIZZARD_API_BASE',
    'SESSION_CONFIG',
]
